### PR TITLE
Integrate Mayhem

### PR DESCRIPTION
**Pull request by rnshah9**

### CODE REVIEW

**Review by xansec — APPROVED** [review]
This is... ok, however the defect seems to be in the example code rather than in the underlying libcyaml source. https://mayhem.forallsecure.com/rnshah9/libcyaml/planner/-/defects/262939.  LGTM!

**Comment by rnshah9** [comment]
If I'm reading this correctly, the defect is a nullref at line 446, which is trying to print `plan->name`. But the `plan` struct was passed into the source function `cyaml_load_file(...)` earlier, which presumably should have resulted in the struct being populated. Is that not a defect with the source code?

**Comment by xansec** [comment]
Right, but I can't necessarily trust that cyaml_load_file will return a valid struct (maybe the file is missing, or corrupt, or there's a TOCTOU issue...). I can add a null check in the example code that will resolve this issue, without touching the underlying source code at all. A source code defect would have to be resolved at the source level. You could argue that the function itself should check if it returns null (or something else), but again there's no contract that explicitly states this.

**Comment by rnshah9** [comment]
Ah, that makes sense. I guess official library example code should exemplify proper error handling patterns, though!

**Comment by xansec** [comment]
As an example, I made the following change:
https://github.com/mayhemheroes/libcyaml/commit/767a1b56fd4ed9ab5f423a7e6300c295c9b15e30

**Pull request merged**
